---
- name: Remove conflicting package.
  package:
    name:
      - speedtest-cli
    state: absent
  when: speedtest_remove_conflicts|bool

- include_tasks: Debian.yml
  when: (ansible_os_family == 'Debian') or (ansible_os_family == 'Ubuntu')

- include_tasks: RedHat.yml
  when: (ansible_os_family == 'RedHat') or (ansible_os_family == 'CentOS') or (ansible_os_family == 'Fedora')